// Estilos inline usados nos formulários e componentes legados
const s = {
  app:  { maxWidth:480, margin:"0 auto", minHeight:"100vh", background:"#FFF0F3", fontFamily:"'DM Sans',sans-serif", color:"#4A1A2C" },
  hdr:  { background:"#4A1A2C", padding:"14px 18px", display:"flex", alignItems:"center", justifyContent:"space-between", position:"sticky", top:0, zIndex:100 },
  logo: { fontFamily:"'Playfair Display',serif", color:"#E8899A", fontSize:17, lineHeight:1.2 },
  lsub: { color:"#D4748866", fontSize:10, letterSpacing:".1em", textTransform:"uppercase" },
  bpri: { background:"#C45C74", color:"#fff", border:"none", borderRadius:50, padding:"8px 16px", fontSize:13, fontWeight:600, cursor:"pointer", fontFamily:"'DM Sans',sans-serif" },
  bback:{ background:"rgba(255,255,255,.12)", border:"none", color:"#fff", borderRadius:50, padding:"7px 14px", fontSize:13, cursor:"pointer" },
  tabs: { display:"flex", borderBottom:"2px solid #F5D0D8", background:"#fff" },
  tab:  { flex:1, padding:"12px 8px", border:"none", background:"none", fontSize:12, fontWeight:600, color:"#7A4A5888", cursor:"pointer", borderBottom:"3px solid transparent", marginBottom:"-2px", fontFamily:"'DM Sans',sans-serif" },
  taba: { color:"#C45C74", borderBottomColor:"#C45C74" },
  srchW:{ margin:"12px 14px 0", position:"relative", display:"block" },
  srch: { width:"100%", padding:"10px 14px 10px 38px", borderRadius:50, border:"2px solid #F5D0D8", background:"#FFF0F3", fontSize:13, color:"#4A1A2C", outline:"none", boxSizing:"border-box", fontFamily:"'DM Sans',sans-serif", display:"block" },
  chips:{ display:"flex", gap:8, padding:"10px 14px", overflowX:"auto", scrollbarWidth:"none" },
  chip: { flexShrink:0, background:"#fff", border:"2px solid #F5D0D8", color:"#7A4A58", borderRadius:50, padding:"5px 12px", fontSize:11, fontWeight:600, cursor:"pointer", fontFamily:"'DM Sans',sans-serif" },
  chipa:{ background:"#4A1A2C", borderColor:"#4A1A2C", color:"#E8899A" },
  cnt:  { padding:"0 18px 6px", fontSize:11, color:"#7A4A5888" },
  list: { padding:"0 14px 100px", display:"flex", flexDirection:"column", gap:10 },
  card: { background:"#fff", borderRadius:14, padding:"12px 14px", display:"flex", alignItems:"center", gap:10, boxShadow:"0 2px 8px rgba(74,26,44,.08)", cursor:"pointer", border:"1.5px solid transparent", transition:"all .15s" },
  cem:  { width:46, height:46, background:"#FFF0F3", borderRadius:12, display:"flex", alignItems:"center", justifyContent:"center", fontSize:24, flexShrink:0 },
  cbd:  { flex:1, minWidth:0 },
  cnm:  { fontWeight:600, fontSize:14, whiteSpace:"nowrap", overflow:"hidden", textOverflow:"ellipsis" },
  cmt:  { fontSize:11, color:"#7A4A58", marginTop:2 },
  cpr:  { textAlign:"right", flexShrink:0 },
  cpv:  { fontFamily:"'Playfair Display',serif", fontSize:15, fontWeight:700, color:"#C45C74" },
  cpl:  { fontSize:10, color:"#7A4A5888" },
  emp:  { textAlign:"center", padding:"60px 20px" },

  // Estilos dos formulários (usados nos drawers)
  sec:  { background:"#fff", borderRadius:10, padding:16, marginBottom:12, border:"1px solid #E5E7EB" },
  st:   { fontSize:13, fontWeight:600, color:"#374151", marginBottom:10 },
  lbl:  { display:"block", fontSize:11, fontWeight:600, color:"#6B7280", textTransform:"uppercase", letterSpacing:".05em", marginBottom:4 },
  inp:  { width:"100%", padding:"9px 12px", borderRadius:8, border:"1.5px solid #E5E7EB", background:"#fff", fontFamily:"'Inter','DM Sans',sans-serif", fontSize:14, color:"#111827", outline:"none", marginBottom:10, boxSizing:"border-box", WebkitAppearance:"none" },
  tag:  { background:"#EFF6FF", borderRadius:7, padding:"5px 9px", fontSize:11, color:"#1D4ED8", fontWeight:600, marginBottom:7, border:"1px solid #BFDBFE" },
  badd: { background:"#F9FAFB", border:"1.5px dashed #D1D5DB", color:"#6B7280", borderRadius:8, padding:10, width:"100%", fontSize:13, fontWeight:600, cursor:"pointer", marginTop:3, fontFamily:"'Inter','DM Sans',sans-serif" },
  bsave:{ background:"#111827", color:"#fff", border:"none", borderRadius:8, padding:"12px 20px", width:"100%", fontFamily:"'Inter','DM Sans',sans-serif", fontSize:14, fontWeight:600, cursor:"pointer" },
  dh:   { background:"#111827", padding:"18px 18px 22px" },
  dn:   { fontSize:20, color:"#fff", fontWeight:700, marginBottom:3 },
  dc:   { fontSize:11, color:"rgba(255,255,255,.55)", textTransform:"uppercase", letterSpacing:".07em" },
  db:   { padding:"12px 12px 100px" },
  ir:   { display:"flex", justifyContent:"space-between", alignItems:"center", padding:"6px 0", borderBottom:"1px solid #F3F4F6", fontSize:13 },
  icost:{ fontWeight:600, color:"#111827", flexShrink:0, marginLeft:6 },
  pg:   { display:"grid", gridTemplateColumns:"1fr 1fr", gap:8, marginBottom:8 },
  pb:   { background:"#F9FAFB", borderRadius:9, padding:"9px 11px", border:"1px solid #E5E7EB" },
  pl:   { fontSize:10, textTransform:"uppercase", letterSpacing:".05em", color:"#6B7280", marginBottom:3 },
  pv:   { fontSize:15, fontWeight:700, color:"#111827" },
  ph:   { background:"#111827", borderRadius:12, padding:"14px 16px", color:"#fff", margin:"7px 0" },
  phl:  { fontSize:11, opacity:.8, marginBottom:3 },
  phv:  { fontSize:26, fontWeight:700 },
  be:   { flex:1, background:"#111827", color:"#fff", border:"none", borderRadius:8, padding:12, fontSize:13, fontWeight:600, cursor:"pointer", fontFamily:"'Inter','DM Sans',sans-serif" },
  bd:   { background:"none", border:"1.5px solid #FCA5A5", color:"#DC2626", borderRadius:8, padding:"11px 16px", fontSize:13, cursor:"pointer", fontFamily:"'Inter','DM Sans',sans-serif" },
  fb:   { padding:"12px 12px 20px" },
  er:   { display:"flex", flexWrap:"wrap", gap:7, marginBottom:12 },
  eb:   { width:38, height:38, borderRadius:9, border:"1.5px solid #E5E7EB", background:"#F9FAFB", fontSize:19, cursor:"pointer" },
  ebs:  { borderColor:"#6366F1", background:"#EEF2FF" },
  ic:   { background:"#F9FAFB", borderRadius:10, padding:12, marginBottom:10, border:"1px solid #E5E7EB" },
  ich:  { display:"flex", justifyContent:"space-between", alignItems:"center", marginBottom:8 },
  brm:  { background:"none", border:"none", color:"#9CA3AF", fontSize:11, cursor:"pointer", fontFamily:"'Inter','DM Sans',sans-serif" },
  help: { fontSize:12, color:"#6B7280", marginBottom:10, lineHeight:1.5, background:"#F3F4F6", borderRadius:7, padding:"7px 10px", borderLeft:"3px solid #D1D5DB" },
  cs:   { background:"#F9FAFB", borderRadius:9, padding:"10px 12px", marginBottom:12, border:"1px solid #E5E7EB" },
  cr:   { display:"flex", justifyContent:"space-between", fontSize:13, padding:"2px 0", color:"#374151" },
  tst:  { position:"fixed", bottom:22, left:"50%", transform:"translateX(-50%)", background:"#111827", color:"#fff", padding:"11px 22px", borderRadius:50, fontSize:13, fontWeight:500, zIndex:300, whiteSpace:"nowrap", boxShadow:"0 4px 18px rgba(0,0,0,.3)" },
  sync: { position:"fixed", top:68, right:10, background:"#374151", color:"#fff", padding:"3px 10px", borderRadius:50, fontSize:10, zIndex:100 },
};

export default s;
